### ISSUE TITLE
Google Chrome Issue

### ISSUE THREAD

**Issue by MinoBibawy** [metalx1000/Basic360#1]
Hi, when i open index.html on google chrome its dident work, but if i open it with firefox yes.

**Comment by metalx1000** [comment]
It's working for me in Chrome Version 73.0.3683.75 (Official Build) (64-bit) on My Desktop.
Are you running this on a mobile or desktop browser?
Does your Error Console in Chrome tell you anything?

**Comment by metalx1000** [comment]
Also just checked in Chrome Version 73.0.3683.75 on my Android Phone.  
Everything is working fine there for me.

**Comment by MinoBibawy** [comment]
im running the same version of you 73.0.3683.75 (Official Build) (64-bit).
it give me a balck page.

**Comment by metalx1000** [comment]
And the error console doesn't say anything in Chrome?
Do you have issues with other ThreeJS projects?
https://threejs.org/

**Comment by MinoBibawy** [comment]
It give me this error THREE.WebGLRenderer.renderBuffer and the location file of the scriot (full path).
but in firefox it work

**Comment by metalx1000** [comment]
I just want to double check, are you running this on a webserver and not just opening the file with a web browser?
It will not work correctly (or at lest shouldn't, although it seems like it does with Firefox) if you are just opening the file locally.  This is to prevent your personal files from being accessed.

If that is the case, please let me know.
If you want to run it like that, you can kill Chrome and restart it like this:
chrome --allow-file-access-from-files

More information here:
https://github.com/mrdoob/three.js/wiki/How-to-run-things-locally

**Comment by MinoBibawy** [comment]
im useing it locally.

**Comment by metalx1000** [comment]
By locally I'm going to assume you mean you don't have a Web-server running (Apache, Python, HTTPD, etc).  So, I'm going to close this ticket out.  

Thanks for the input.  I hope you get a lot of use out of the script.
